language: python
python:
- "2.6"
- "2.7"
install:
# Install dependencies
- sudo apt-get update
- sudo apt-get install -y zsh pinentry-curses steghide gnupg 
- git clone https://github.com/dyne/Tomb && cd Tomb && sudo make install
- cd /home/travis/build/reiven/tomber
script:
# Normal tests
- nosetests -v
notifications:
  email:
    recipients:
      - reiven@gmail.com
    on_success: [always|never|change] # default: change
    on_failure: [always|never|change] # default: always