language: python
python:
- "2.6"
- "2.7"
install:
# Install dependencies
- sudo apt-get update
- sudo apt-get install -y zsh pinentry-curses steghide gnupg cryptsetup
- git clone https://github.com/dyne/Tomb && cd Tomb && sudo make install && cd ..
- pwd
# check of Tomb was installed ok
- tomb help
- tomb dig test.tomb -s10
script:
# Normal tests
- nosetests -v
notifications:
  email:
    recipients:
      - reiven@gmail.com
    on_success: change # default: change
    on_failure: always # default: always